### ISSUE TITLE
Code doesn't run, even -h not

### ISSUE THREAD

**Issue by tradox** [teplinsky-maxim/spotify-playlist-downloader#1]
C:\Users\user\Downloads\spotify-playlist-downloader-master>python main.py -h
Traceback (most recent call last):
  File "C:\Users\user\Downloads\spotify-playlist-downloader-master\main.py", line 5, in <module>
    from core.downloader.soundloader.soundloader import SoundLoaderDownloader
  File "C:\Users\user\Downloads\spotify-playlist-downloader-master\core\downloader\soundloader\soundloader.py", line 11, in <module>
    class SoundLoaderDownloader(DownloaderBase):
  File "C:\Users\user\Downloads\spotify-playlist-downloader-master\core\downloader\soundloader\soundloader.py", line 37, in SoundLoaderDownloader
    async def _get_download_path(self, track_id: str, etag: str) -> tuple[dict | None, str]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

how to fix this?

**Comment by teplinsky-maxim** [comment]
@tradox, the code is written in Python 3.10, so to start the code you need to install 3.10+ or downgrade typing to 3.9 or lower versions

**Comment by teplinsky-maxim** [comment]
I've updated the readme

**Comment by tradox** [comment]
thx for quick reply, the code works with Union from typing and python version 3.9.7

like this:
def _get_headers(content_type: Union[str, None] = None, etag: Union[str, None] = None) -> dict:

**Comment by teplinsky-maxim** [comment]
No problem! Btw, you can also use `Optional[str]` instead of `Union[str, None]` I believe
