### ISSUE TITLE
The script was working, then suddenly stopped working and slowly got worse.

### ISSUE THREAD

**Issue by Extrememasters1** [teplinsky-maxim/spotify-playlist-downloader#2]
When I first downloaded this it worked perfectly for a couple weeks, then one day I tried to use it and it would take an hour to download 10 songs. A week or so later tried again and it downloaded instantly all songs but each mp3 was just 1:33 long silence. Now when I try to use it I get this response.

Extracting from https://open.spotify.com/playlist/3vnn5aBbZJc7zn0zLnUqdU ...
... 16 songs found
FIRST_COMPLETED
Traceback (most recent call last):
  File "C:\Users\Logan\Desktop\SpotifyScript\spotify-playlist-downloader-master\main.py", line 59, in <module>
    asyncio.run(main())
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Logan\Desktop\SpotifyScript\spotify-playlist-downloader-master\main.py", line 55, in main
    await process(args.playlist, args.dir, args.threads)
  File "C:\Users\Logan\Desktop\SpotifyScript\spotify-playlist-downloader-master\main.py", line 31, in process
    url, result = item.result()
  File "C:\Users\Logan\Desktop\SpotifyScript\spotify-playlist-downloader-master\core\downloader\soundloader\soundloader.py", line 18, in download
    downloader_metadata, etag = await self._start_download(track_metadata)
  File "C:\Users\Logan\Desktop\SpotifyScript\spotify-playlist-downloader-master\core\downloader\soundloader\soundloader.py", line 92, in _start_download
    data = await resp.json()
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.soundloaders.com/download/track')

**Comment by jordanwmcdonald** [comment]
Yes, first time using and I have this exact issue.

**Comment by teplinsky-maxim** [comment]
The API of the site has changed, the script needs to be updated too. I do not have much time to do this rn, probably will be fixed later. Any help will be appreciated 🙌
